export {
  EMPTY_RECT,
  ORIGIN,
  addPoints,
  boundsOfPoints,
  clamp,
  distance,
  distanceToPolyline,
  distanceToSegment,
  inflateRect,
  midpoint,
  pathLength,
  pointAtLength,
  rectBorderPoint,
  rectBottom,
  rectCenter,
  rectContains,
  rectContainsRect,
  rectOf,
  rectRight,
  rectSize,
  rectUnion,
  rectsIntersect,
  scalePoint,
  segmentNormal,
  unionAll,
} from './geometry.js';
export type { Point, Rect, Size } from './geometry.js';
